### ISSUE TITLE
Traceback Error updating sensor, is kodi running?

### ISSUE THREAD

**Issue by roumano** [boralyl/kodi-recently-added#12]
**Describe the bug**
When the kodi is not power-on (aka when the computer or the TV is not started) i got a Traceback of `custom_components.kodi_media_sensors.entities`

**To Reproduce**
1. Configure kodi_media_sensors
2. poweroff the computer/TV where the kodi is started
3. See error
```
ERROR (MainThread) [custom_components.kodi_media_sensors.entities] Error updating sensor, is kodi running?
 Traceback (most recent call last):
   File "/data/homeassistant/.homeassistant/custom_components/kodi_media_sensors/entities.py", line 44, in async_update
     result = await self.kodi.call_method(
   File "/data/homeassistant/lib/python3.10/site-packages/pykodi/kodi.py", line 294, in call_method
     return await getattr(self._server, method)(**kwargs)
   File "/data/homeassistant/lib/python3.10/site-packages/jsonrpc_websocket/jsonrpc.py", line 42, in send_message
     raise TransportError('Client is not connected.', message)
 jsonrpc_base.jsonrpc.TransportError: Error calling method 'VideoLibrary.GetRecentlyAddedEpisodes': Client is not connected.
 2021-12-08 17:10:40 ERROR (MainThread) [custom_components.kodi_media_sensors.entities] Error updating sensor, is kodi running?
 Traceback (most recent call last):
   File "/data/homeassistant/.homeassistant/custom_components/kodi_media_sensors/entities.py", line 44, in async_update
     result = await self.kodi.call_method(
   File "/data/homeassistant/lib/python3.10/site-packages/pykodi/kodi.py", line 294, in call_method
     return await getattr(self._server, method)(**kwargs)
   File "/data/homeassistant/lib/python3.10/site-packages/jsonrpc_websocket/jsonrpc.py", line 42, in send_message
     raise TransportError('Client is not connected.', message)
 jsonrpc_base.jsonrpc.TransportError: Error calling method 'VideoLibrary.GetRecentlyAddedMovies': Client is not connected.
```

**Expected behavior**
kodi_media_sensors should detect the kodi is not started or not (the `entity: media_player.kodi...` detect this behavior nicely ) and doesn't try to refresh the database

**Home Assistant and Custom Component versions (please complete the following information):**
Home Assistant version: 2021.11.5
kodi-recently-added component version: 3.1.5

**Additional context**

**Comment by boralyl** [comment]
Fixed by 5433e49 in v2.0.5
